#!/usr/bin/env bash

TOKEN=""
ID=""
CONFIG_FILE="$HOME/.teledove.conf"

if [ -f $CONFIG_FILE ]
then
    . $CONFIG_FILE
fi

get_url () {
    if hash curl 2>/dev/null
    then
        curl -sS "$1"
    elif hash wget 2>/dev/null
    then
        wget -qO- "$1"
    else
        echo "No command line url program found. Please install curl or wget" >&2
        exit 1
    fi
}

if [ -z "$TOKEN" ]
then
    TOKEN_SET=0
    while [ $TOKEN_SET -eq 0 ]
    do
        echo "Please provide Telegram Bot token"
        read TOKEN
        if [[ $TOKEN == *":"* && ${#TOKEN} -gt 30 ]]
        then
           TOKEN_SET=1
           echo "Token set and stored in $CONFIG_FILE"
       else
           echo "That does not look like a valid token. Please try again"
       fi
    done
    echo "TOKEN=$TOKEN" > $CONFIG_FILE
    ID=""
fi 

if [ -z "$ID" ]
then
    echo "Fetching chat ID"
    ID_QUERY=$(get_url "https://api.telegram.org/bot$TOKEN/getUpdates") 
    NAME=$(echo "$ID_QUERY" | grep -Po "(?<=\"first_name\":)\".+?\"" | tail -1)
    ID=$(echo "$ID_QUERY" | grep -Po "(?<=\"id\":)\d+" | tail -1)
    if [ -z "$ID" ]
    then
        echo "No chat ID found. Start communicating with bot/send a message and try again"
        rm $CONFIG_FILE
        exit 1
    fi
    echo "Chat ID found and stored in $CONFIG_FILE"
    echo "Established connection with $NAME"
    echo "ID=$ID" >> $CONFIG_FILE
fi


MESSAGE_URL="https://api.telegram.org/bot$TOKEN/sendMessage?chat_id=$ID"
if [ $# -eq 0 ]
then
    MESSAGE="Alert from $(hostname)"
else
    MESSAGE="$@"
fi
RESPONSE=$(get_url "$MESSAGE_URL&text=$MESSAGE")
if [[ $RESPONSE == *"\"ok\":false"* ]]
then
    echo "Alert failed. Please check if 1) the Telegram Bot is up and running and 2) you have send a message to this bot before"
    echo "Deleting cache, please try again"
    rm $CONFIG_FILE
    exit 1
fi
